name: video_share
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^5.0.0
  cloud_firestore: ^1.0.4
  connectivity: ^3.0.3
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  firebase_storage: 
  image_picker: ^0.7.4
  video_compress: ^3.0.0
  uuid: ^3.0.4
  cached_network_image: ^3.0.0
  multi_image_picker: ^4.8.0
  flutter_image_compress: ^1.0.0
  flutter_absolute_path: ^1.0.6


  google_fonts:
  video_player:




  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:

  assets:
    - assets/images/
    
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf


  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
